import re


CATALOGUE_CODE_PATTERN = re.compile(
    r"^[a-z][a-z0-9_]*$"
)

MAX_CATALOGUE_CODE_LENGTH = 64
MAX_CATALOGUE_NAME_LENGTH = 120
MAX_CATALOGUE_DESCRIPTION_LENGTH = 500
MAX_CATALOGUE_ICON_LENGTH = 120
MAX_CATALOGUE_COLOUR_LENGTH = 7

DEFAULT_CATALOGUE_ICON = "tabler:list"
DEFAULT_CATALOGUE_COLOUR = "#334155"
DEFAULT_CATALOGUE_SORT_ORDER = 0