"""Technical constants for the Event Journal."""

EVENT_CODE_MAX_LENGTH = 120
JOURNAL_SUMMARY_MAX_LENGTH = 500
JOURNAL_DETAILS_MAX_LENGTH = 10_000

JOURNAL_EVENT_CODE_PATTERN = (
    r"^[a-z][a-z0-9_]*\."
    r"[a-z][a-z0-9_]*$"
)

JOURNAL_REFERENCE_TYPE_MAX_LENGTH = 100
JOURNAL_REFERENCE_DISPLAY_NAME_MAX_LENGTH = 255
JOURNAL_REFERENCE_STABLE_KEY_MAX_LENGTH = 200

JOURNAL_REFERENCE_TYPE_PATTERN = (
    r"^[a-z][a-z0-9_]*$"
)

JOURNAL_REFERENCE_STABLE_KEY_PATTERN = (
    r"^[a-z0-9][a-z0-9:_-]*$"
)


__all__ = [
    "EVENT_CODE_MAX_LENGTH",
    "JOURNAL_DETAILS_MAX_LENGTH",
    "JOURNAL_REFERENCE_TYPE_MAX_LENGTH",
    "JOURNAL_REFERENCE_DISPLAY_NAME_MAX_LENGTH",
    "JOURNAL_REFERENCE_STABLE_KEY_MAX_LENGTH",
    "JOURNAL_REFERENCE_TYPE_PATTERN",
    "JOURNAL_REFERENCE_STABLE_KEY_PATTERN",
    "JOURNAL_EVENT_CODE_PATTERN",
    "JOURNAL_SUMMARY_MAX_LENGTH",
]