"""Add Journal references

Revision ID: 26678d59576f
Revises: ca7b7fcb082b
Create Date: 2026-08-03 21:50:10.974821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26678d59576f'
down_revision = 'ca7b7fcb082b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference_type', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('stable_key', sa.String(length=200), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(display_name) > 0', name=op.f('ck_journal_references_ck_journal_references_display_name_not_empty')),
    sa.CheckConstraint('char_length(reference_type) > 0', name=op.f('ck_journal_references_ck_journal_references_type_not_empty')),
    sa.CheckConstraint('source_id IS NOT NULL OR stable_key IS NOT NULL', name=op.f('ck_journal_references_ck_journal_references_identity_required')),
    sa.CheckConstraint('stable_key IS NULL OR stable_key = lower(stable_key)', name=op.f('ck_journal_references_ck_journal_references_stable_key_lowercase')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_references'))
    )
    with op.batch_alter_table('journal_references', schema=None) as batch_op:
        batch_op.create_index('ix_journal_references_type', ['reference_type'], unique=False)
        batch_op.create_index('uq_journal_references_type_source', ['reference_type', 'source_id'], unique=True, postgresql_where=sa.text('source_id IS NOT NULL'))
        batch_op.create_index('uq_journal_references_type_stable_key', ['reference_type', 'stable_key'], unique=True, postgresql_where=sa.text('stable_key IS NOT NULL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_references', schema=None) as batch_op:
        batch_op.drop_index('uq_journal_references_type_stable_key', postgresql_where=sa.text('stable_key IS NOT NULL'))
        batch_op.drop_index('uq_journal_references_type_source', postgresql_where=sa.text('source_id IS NOT NULL'))
        batch_op.drop_index('ix_journal_references_type')

    op.drop_table('journal_references')
    # ### end Alembic commands ###
