"""Add Journal Entry references and Desk context

Revision ID: 3afc18cd9cdd
Revises: 26678d59576f
Create Date: 2026-08-03 22:12:32.380993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3afc18cd9cdd'
down_revision = '26678d59576f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor_reference_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('subject_reference_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('context_reference_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('desk_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('desk_display_name', sa.String(length=200), nullable=True))
        batch_op.create_index('ix_journal_entries_actor_occurred_at', ['actor_reference_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_actor_reference_id'), ['actor_reference_id'], unique=False)
        batch_op.create_index('ix_journal_entries_context_occurred_at', ['context_reference_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_context_reference_id'), ['context_reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_desk_id'), ['desk_id'], unique=False)
        batch_op.create_index('ix_journal_entries_desk_occurred_at', ['desk_id', 'occurred_at'], unique=False)
        batch_op.create_index('ix_journal_entries_subject_occurred_at', ['subject_reference_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_subject_reference_id'), ['subject_reference_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_journal_entries_desk_id_desks'), 'desks', ['desk_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_journal_entries_subject_reference_id_journal_references'), 'journal_references', ['subject_reference_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_journal_entries_context_reference_id_journal_references'), 'journal_references', ['context_reference_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_journal_entries_actor_reference_id_journal_references'), 'journal_references', ['actor_reference_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_journal_entries_actor_reference_id_journal_references'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_journal_entries_context_reference_id_journal_references'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_journal_entries_subject_reference_id_journal_references'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_journal_entries_desk_id_desks'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_journal_entries_subject_reference_id'))
        batch_op.drop_index('ix_journal_entries_subject_occurred_at')
        batch_op.drop_index('ix_journal_entries_desk_occurred_at')
        batch_op.drop_index(batch_op.f('ix_journal_entries_desk_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_context_reference_id'))
        batch_op.drop_index('ix_journal_entries_context_occurred_at')
        batch_op.drop_index(batch_op.f('ix_journal_entries_actor_reference_id'))
        batch_op.drop_index('ix_journal_entries_actor_occurred_at')
        batch_op.drop_column('desk_display_name')
        batch_op.drop_column('desk_id')
        batch_op.drop_column('context_reference_id')
        batch_op.drop_column('subject_reference_id')
        batch_op.drop_column('actor_reference_id')

    # ### end Alembic commands ###
