"""align hierarchical location schema

Revision ID: 3c3c38fc6853
Revises: db2d9792bbb5
Create Date: 2026-07-26 07:39:18.960697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c3c38fc6853'
down_revision = 'db2d9792bbb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisation_locations', schema=None) as batch_op:
        batch_op.alter_column('address_line_1',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('town_city',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_index('uq_organisation_locations_primary_type', postgresql_where='(is_primary IS TRUE)')
        batch_op.create_unique_constraint('uq_organisation_locations_org_code', ['organisation_id', 'code'])
        batch_op.create_index('uq_organisation_locations_single_primary', ['organisation_id'], unique=True, postgresql_where=sa.text('is_primary IS TRUE'))
        batch_op.drop_column('location_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisation_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_type', sa.VARCHAR(length=50), server_default=sa.text("'operational_base'::character varying"), autoincrement=False, nullable=False))
        batch_op.drop_index('uq_organisation_locations_single_primary', postgresql_where=sa.text('is_primary IS TRUE'))
        batch_op.drop_constraint('uq_organisation_locations_org_code', type_='unique')
        batch_op.create_index('uq_organisation_locations_primary_type', ['organisation_id', 'location_type'], unique=True, postgresql_where='(is_primary IS TRUE)')
        batch_op.alter_column('town_city',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('address_line_1',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
