"""expand organisation profile and add locations

Revision ID: 64ae04c90b0b
Revises: b4a00bdd399e
Create Date: 2026-07-25 20:44:34.096527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ae04c90b0b'
down_revision = 'b4a00bdd399e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location_type', sa.String(length=50), server_default='operational_base', nullable=False),
    sa.Column('address_line_1', sa.String(length=255), nullable=False),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('address_line_3', sa.String(length=255), nullable=True),
    sa.Column('town_city', sa.String(length=120), nullable=False),
    sa.Column('county_region', sa.String(length=120), nullable=True),
    sa.Column('postcode', sa.String(length=20), nullable=True),
    sa.Column('country_code', sa.String(length=2), server_default='GB', nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_organisation_locations_organisation_id_organisations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organisation_locations'))
    )
    with op.batch_alter_table('organisation_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organisation_locations_organisation_id'), ['organisation_id'], unique=False)
        batch_op.create_index('uq_organisation_locations_primary_type', ['organisation_id', 'location_type'], unique=True, postgresql_where=sa.text('is_primary IS TRUE'))

    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legal_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('service_type', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('provider_reference', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('company_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('charity_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('vat_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('general_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('general_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('website_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('country_code', sa.String(length=2), server_default='GB', nullable=False))
        batch_op.add_column(sa.Column('timezone', sa.String(length=64), server_default='Europe/London', nullable=False))
        batch_op.add_column(sa.Column('locale', sa.String(length=20), server_default='en-GB', nullable=False))
        batch_op.add_column(sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.alter_column('region',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.create_unique_constraint(batch_op.f('uq_organisations_charity_number'), ['charity_number'])
        batch_op.create_unique_constraint(batch_op.f('uq_organisations_company_number'), ['company_number'])
        batch_op.create_unique_constraint(batch_op.f('uq_organisations_provider_reference'), ['provider_reference'])
        batch_op.create_index('uq_organisations_single_primary', ['is_primary'], unique=True, postgresql_where=sa.text('is_primary IS TRUE'))
        batch_op.create_unique_constraint(batch_op.f('uq_organisations_vat_number'), ['vat_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_organisations_vat_number'), type_='unique')
        batch_op.drop_index('uq_organisations_single_primary', postgresql_where=sa.text('is_primary IS TRUE'))
        batch_op.drop_constraint(batch_op.f('uq_organisations_provider_reference'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_organisations_company_number'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_organisations_charity_number'), type_='unique')
        batch_op.alter_column('region',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('is_primary')
        batch_op.drop_column('locale')
        batch_op.drop_column('timezone')
        batch_op.drop_column('country_code')
        batch_op.drop_column('website_url')
        batch_op.drop_column('general_phone')
        batch_op.drop_column('general_email')
        batch_op.drop_column('vat_number')
        batch_op.drop_column('charity_number')
        batch_op.drop_column('company_number')
        batch_op.drop_column('provider_reference')
        batch_op.drop_column('service_type')
        batch_op.drop_column('legal_name')

    with op.batch_alter_table('organisation_locations', schema=None) as batch_op:
        batch_op.drop_index('uq_organisation_locations_primary_type', postgresql_where=sa.text('is_primary IS TRUE'))
        batch_op.drop_index(batch_op.f('ix_organisation_locations_organisation_id'))

    op.drop_table('organisation_locations')
    # ### end Alembic commands ###
