"""Add file object storage records

Revision ID: 82c0fcdf3dc6
Revises: e758c8e328f1
Create Date: 2026-08-01 07:38:40.969065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82c0fcdf3dc6'
down_revision = 'e758c8e328f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('storage_backend', sa.String(length=32), server_default='s3', nullable=False),
    sa.Column('bucket', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=255), server_default='application/octet-stream', nullable=False),
    sa.Column('extension', sa.String(length=32), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('char_length(sha256) = 64', name=op.f('ck_file_objects_ck_file_objects_sha256_length')),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_file_objects_ck_file_objects_size_bytes_non_negative')),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['user_accounts.id'], name=op.f('fk_file_objects_uploaded_by_id_user_accounts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_objects')),
    sa.UniqueConstraint('bucket', 'object_key', name='uq_file_objects_bucket_object_key')
    )
    with op.batch_alter_table('file_objects', schema=None) as batch_op:
        batch_op.create_index('ix_file_objects_active', ['created_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
        batch_op.create_index('ix_file_objects_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_file_objects_sha256', ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_objects_uploaded_by_id'), ['uploaded_by_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_objects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_objects_uploaded_by_id'))
        batch_op.drop_index('ix_file_objects_sha256')
        batch_op.drop_index('ix_file_objects_created_at')
        batch_op.drop_index('ix_file_objects_active', postgresql_where=sa.text('deleted_at IS NULL'))

    op.drop_table('file_objects')
    # ### end Alembic commands ###
