"""add user display name

Revision ID: 92173a9e098c
Revises: 20260724_initial_schema
Create Date: 2026-07-25 05:59:34.531476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92173a9e098c'
down_revision: Union[str, None] = '20260724_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('first_name', sa.String(length=255), nullable=False))
    op.add_column('user_accounts', sa.Column('last_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_accounts', 'last_name')
    op.drop_column('user_accounts', 'first_name')
    # ### end Alembic commands ###
