"""Add Desk archival state

Revision ID: 9956df3c7b21
Revises: f8067fe21340
Create Date: 2026-08-03 17:45:52.906000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9956df3c7b21'
down_revision = 'f8067fe21340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('desks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_desks_archived_at'), ['archived_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('desks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_desks_archived_at'))
        batch_op.drop_column('archived_at')

    # ### end Alembic commands ###
