"""extend roles for access management

Revision ID: b2cca998df42
Revises: 3c3c38fc6853
Create Date: 2026-07-26 09:32:22.394858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2cca998df42'
down_revision = '3c3c38fc6853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=120), server_default='', nullable=False))
        batch_op.add_column(sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    op.execute(
        """
        UPDATE roles
        SET display_name = INITCAP(
            REPLACE(name, '_', ' ')
        )
        WHERE display_name = ''
        """
    )

    op.execute(
        """
        UPDATE roles
        SET
            display_name = 'Administrator',
            is_system = TRUE,
            is_active = TRUE,
            sort_order = 10
        WHERE name = 'admin'
        """ 
    )

    op.execute(
        """
        UPDATE roles
        SET
            display_name = 'Staff',
            is_system = TRUE,
            is_active = TRUE,
            sort_order = 20
        WHERE name = 'staff'
        """
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('sort_order')
        batch_op.drop_column('is_active')
        batch_op.drop_column('is_system')
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
