"""Add initial Event Journal

Revision ID: ca7b7fcb082b
Revises: 9956df3c7b21
Create Date: 2026-08-03 21:16:46.052873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca7b7fcb082b'
down_revision = '9956df3c7b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_code', sa.String(length=120), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(event_code) > 0', name=op.f('ck_journal_entries_ck_journal_entries_event_code_not_empty')),
    sa.CheckConstraint('char_length(summary) > 0', name=op.f('ck_journal_entries_ck_journal_entries_summary_not_empty')),
    sa.CheckConstraint('event_code = lower(event_code)', name=op.f('ck_journal_entries_ck_journal_entries_event_code_lowercase')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_entries'))
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_event_code'), ['event_code'], unique=False)
        batch_op.create_index('ix_journal_entries_event_code_occurred_at', ['event_code', 'occurred_at'], unique=False)
        batch_op.create_index('ix_journal_entries_occurred_at', ['occurred_at'], unique=False)
        batch_op.create_index('ix_journal_entries_recorded_at', ['recorded_at'], unique=False)

    with op.batch_alter_table('desks', schema=None) as batch_op:
        batch_op.drop_index('ix_desks_active_name')
        batch_op.create_index('ix_desks_active_name', ['archived_at', 'is_active', 'name'], unique=False)
        batch_op.drop_index('ix_desks_parent_active_name')
        batch_op.create_index('ix_desks_parent_active_name', ['parent_id', 'archived_at', 'is_active', 'name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('desks', schema=None) as batch_op:
        batch_op.drop_index('ix_desks_parent_active_name')
        batch_op.create_index('ix_desks_parent_active_name', ['parent_id', 'is_active', 'name'], unique=False)
        batch_op.drop_index('ix_desks_active_name')
        batch_op.create_index('ix_desks_active_name', ['is_active', 'name'], unique=False)

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_journal_entries_recorded_at')
        batch_op.drop_index('ix_journal_entries_occurred_at')
        batch_op.drop_index('ix_journal_entries_event_code_occurred_at')
        batch_op.drop_index(batch_op.f('ix_journal_entries_event_code'))

    op.drop_table('journal_entries')
    # ### end Alembic commands ###
