"""add hierarchical locations and capabilities

Revision ID: db2d9792bbb5
Revises: 64ae04c90b0b
Create Date: 2026-07-26 07:17:14.609760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db2d9792bbb5'
down_revision = '64ae04c90b0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_capabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=120), server_default='tabler:map-pin', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location_capabilities')),
    sa.UniqueConstraint('code', name=op.f('uq_location_capabilities_code')),
    sa.UniqueConstraint('name', name=op.f('uq_location_capabilities_name'))
    )
    op.create_table('location_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=120), server_default='tabler:map-pin', nullable=False),
    sa.Column('is_physical', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('can_have_children', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('requires_address', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location_types')),
    sa.UniqueConstraint('code', name='uq_location_types_code'),
    sa.UniqueConstraint('name', name='uq_location_types_name')
    )
    op.create_table('location_type_capabilities',
    sa.Column('location_type_id', sa.UUID(), nullable=False),
    sa.Column('capability_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['location_capabilities.id'], name=op.f('fk_location_type_capabilities_capability_id_location_capabilities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_type_id'], ['location_types.id'], name=op.f('fk_location_type_capabilities_location_type_id_location_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_type_id', 'capability_id', name=op.f('pk_location_type_capabilities'))
    )
    op.create_table('organisation_location_capabilities',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('capability_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['location_capabilities.id'], name=op.f('fk_organisation_location_capabilities_capability_id_location_capabilities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['organisation_locations.id'], name=op.f('fk_organisation_location_capabilities_location_id_organisation_locations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'capability_id', name=op.f('pk_organisation_location_capabilities'))
    )
    with op.batch_alter_table('organisation_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('location_type_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('has_own_address', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.create_index(batch_op.f('ix_organisation_locations_location_type_id'), ['location_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organisation_locations_parent_id'), ['parent_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_organisation_locations_parent_id_organisation_locations'), 'organisation_locations', ['parent_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_organisation_locations_location_type_id_location_types'), 'location_types', ['location_type_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisation_locations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_organisation_locations_location_type_id_location_types'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_organisation_locations_parent_id_organisation_locations'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_organisation_locations_parent_id'))
        batch_op.drop_index(batch_op.f('ix_organisation_locations_location_type_id'))
        batch_op.drop_column('has_own_address')
        batch_op.drop_column('sort_order')
        batch_op.drop_column('description')
        batch_op.drop_column('code')
        batch_op.drop_column('location_type_id')
        batch_op.drop_column('parent_id')

    op.drop_table('organisation_location_capabilities')
    op.drop_table('location_type_capabilities')
    op.drop_table('location_types')
    op.drop_table('location_capabilities')
    # ### end Alembic commands ###
