"""Add Desk hierarchy

Revision ID: f8067fe21340
Revises: 692678d38905
Create Date: 2026-08-02 22:21:32.553478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8067fe21340'
down_revision = '692678d38905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('is_root', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            (\n                is_root = true\n                AND parent_id IS NULL\n            )\n            OR\n            (\n                is_root = false\n                AND parent_id IS NOT NULL\n            )\n            ', name=op.f('ck_desks_ck_desks_root_parent_consistency')),
    sa.CheckConstraint('char_length(code) > 0', name=op.f('ck_desks_ck_desks_code_not_empty')),
    sa.CheckConstraint('char_length(name) > 0', name=op.f('ck_desks_ck_desks_name_not_empty')),
    sa.CheckConstraint('code = lower(code)', name=op.f('ck_desks_ck_desks_code_lowercase')),
    sa.CheckConstraint('parent_id IS NULL OR parent_id <> id', name=op.f('ck_desks_ck_desks_not_own_parent')),
    sa.ForeignKeyConstraint(['parent_id'], ['desks.id'], name=op.f('fk_desks_parent_id_desks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_desks'))
    )
    with op.batch_alter_table('desks', schema=None) as batch_op:
        batch_op.create_index('ix_desks_active_name', ['is_active', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_desks_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_desks_is_active'), ['is_active'], unique=False)
        batch_op.create_index('ix_desks_parent_active_name', ['parent_id', 'is_active', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_desks_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index('uq_desks_single_root', ['is_root'], unique=True, postgresql_where=sa.text('is_root = true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('desks', schema=None) as batch_op:
        batch_op.drop_index('uq_desks_single_root', postgresql_where=sa.text('is_root = true'))
        batch_op.drop_index(batch_op.f('ix_desks_parent_id'))
        batch_op.drop_index('ix_desks_parent_active_name')
        batch_op.drop_index(batch_op.f('ix_desks_is_active'))
        batch_op.drop_index(batch_op.f('ix_desks_code'))
        batch_op.drop_index('ix_desks_active_name')

    op.drop_table('desks')
    # ### end Alembic commands ###
