"""Add file processing policies

Revision ID: fcb06a12b44b
Revises: 82c0fcdf3dc6
Create Date: 2026-08-01 13:24:35.213836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb06a12b44b'
down_revision = '82c0fcdf3dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_processing_policies',
    sa.Column('category', sa.String(length=32), server_default='generic', nullable=False),
    sa.Column('max_size_bytes', sa.BigInteger(), server_default='26214400', nullable=False),
    sa.Column('requires_virus_scan', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('generate_thumbnail', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('generate_preview', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('enable_ocr', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('optimise_image', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('extract_metadata', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=120), server_default='tabler:list', nullable=False),
    sa.Column('colour', sa.String(length=7), server_default='#334155', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_size_bytes > 0', name=op.f('ck_file_processing_policies_ck_file_processing_policies_max_size_bytes_positive')),
    sa.CheckConstraint('sort_order >= 0', name=op.f('ck_file_processing_policies_ck_file_processing_policies_sort_order_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_processing_policies')),
    sa.UniqueConstraint('code', name=op.f('uq_file_processing_policies_code')),
    sa.UniqueConstraint('name', name='uq_file_processing_policies_name')
    )
    with op.batch_alter_table('file_processing_policies', schema=None) as batch_op:
        batch_op.create_index('ix_file_processing_policies_active_order', ['is_active', 'sort_order', 'name'], unique=False)

    op.create_table('file_processing_extension_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('processing_policy_id', sa.UUID(), nullable=False),
    sa.Column('extension', sa.String(length=32), nullable=False),
    sa.CheckConstraint('char_length(extension) > 0', name=op.f('ck_file_processing_extension_rules_ck_file_processing_extension_rules_extension_not_empty')),
    sa.CheckConstraint('extension = lower(extension)', name=op.f('ck_file_processing_extension_rules_ck_file_processing_extension_rules_extension_lowercase')),
    sa.ForeignKeyConstraint(['processing_policy_id'], ['file_processing_policies.id'], name=op.f('fk_file_processing_extension_rules_processing_policy_id_file_processing_policies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_processing_extension_rules')),
    sa.UniqueConstraint('processing_policy_id', 'extension', name='uq_file_processing_extension_rules_policy_extension')
    )
    with op.batch_alter_table('file_processing_extension_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_processing_extension_rules_processing_policy_id'), ['processing_policy_id'], unique=False)

    op.create_table('file_processing_mime_type_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('processing_policy_id', sa.UUID(), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.CheckConstraint("position('/' in mime_type) > 1", name=op.f('ck_file_processing_mime_type_rules_ck_file_processing_mime_type_rules_mime_type_format')),
    sa.CheckConstraint('mime_type = lower(mime_type)', name=op.f('ck_file_processing_mime_type_rules_ck_file_processing_mime_type_rules_mime_type_lowercase')),
    sa.ForeignKeyConstraint(['processing_policy_id'], ['file_processing_policies.id'], name=op.f('fk_file_processing_mime_type_rules_processing_policy_id_file_processing_policies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_processing_mime_type_rules')),
    sa.UniqueConstraint('processing_policy_id', 'mime_type', name='uq_file_processing_mime_type_rules_policy_mime_type')
    )
    with op.batch_alter_table('file_processing_mime_type_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_processing_mime_type_rules_processing_policy_id'), ['processing_policy_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_processing_mime_type_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_processing_mime_type_rules_processing_policy_id'))

    op.drop_table('file_processing_mime_type_rules')
    with op.batch_alter_table('file_processing_extension_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_processing_extension_rules_processing_policy_id'))

    op.drop_table('file_processing_extension_rules')
    with op.batch_alter_table('file_processing_policies', schema=None) as batch_op:
        batch_op.drop_index('ix_file_processing_policies_active_order')

    op.drop_table('file_processing_policies')
    # ### end Alembic commands ###
